select * from avo;
select * from avoa;
select * from neto;
select nome, idade  from neto;
select * from neto order by nome asc;
select * from neto where nome = " Isabela Lima";
select * from neto where idade >= 18;
select * from neto where idade <18;
select * from neto where idade between 10 and 18;
select * from avo order by nome asc;
select * from avoa order by nome asc;
select nome from neto;
select count(*) from neto;
select count(*) from avo;
select count(*) from avoa;
DESC neto;
select neto.nome, avo.nome from neto inner join avo on neto.avo_id = avo.avo_id;
select neto.nome, avoa.nome from neto inner join avoa on neto.avoa_id = avoa.avoa_id;
select neto.nome, avo.nome, avoa.nome from neto inner join avo on neto.avo_id = avo.avo_id inner join avoa on neto.avoa_id = avoa.avoa_id;
select neto.nome, avo.nome from neto inner join avo on neto.avo_id = avo.avo_id where avo.nome = "Antonio Silva";
select neto.nome, avoa.nome from neto inner join avoa on neto.avoa_id = avoa.avoa_id where avoa.nome = " Rosa Martins ";